/* COMMAND_LIMITS */
#define COMMAND_LENGTH 512
#define MAX_COMMANDS_PER_LINE 100
#define SIZE_OF_COMMAND 1024
#define MAX_PROMPT_LENGTH 5120

/* PATH LIMITS */
#define MAX_PATH_LENGTH 4096


/* SYSTEM DEVICE LIMITS : FILES/DIRECTORIES */
#define MAX_FILE_NAME 1024


/* History */
#define MAX_HISTORY 10
#define HISTORY_MEMORY 20
